export interface Essay {
  id: string
  title: string
  author: string
  classLevel: string
  category: string
  summary: string
  views: number
  date: string
}

export const mockEssays: Essay[] = [
  {
    id: '1',
    title: 'Người bạn của tôi',
    author: 'Học sinh lớp 6',
    classLevel: '6',
    category: 'biểu cảm',
    summary: 'Bài văn miêu tả về một người bạn thân thiết, những kỷ niệm đẹp cùng nhau qua những năm học. Bài văn thể hiện tình bạn quý báu...',
    views: 1250,
    date: '2024-06-15',
  },
  {
    id: '2',
    title: 'Ngày hội thể thao của trường',
    author: 'Ngân Hà',
    classLevel: '6',
    category: 'tự sự',
    summary: 'Kể lại những sự kiện chính của ngày hội thể thao, từ lúc đầu cho tới khi kết thúc. Chi tiết hóa các cuộc thi đấu căng thẳng...',
    views: 890,
    date: '2024-06-10',
  },
  {
    id: '3',
    title: 'Con mèo nhà tôi',
    author: 'Minh Anh',
    classLevel: '6',
    category: 'thuyết minh',
    summary: 'Giới thiệu đặc điểm hình thái, tập tính sinh sống của con mèo. Mô tả chi tiết về ngoại hình, cách ăn ở, những thói quen của nó...',
    views: 2100,
    date: '2024-06-08',
  },
  {
    id: '4',
    title: 'Tầm quan trọng của việc học tập',
    author: 'Hoàng Minh',
    classLevel: '7',
    category: 'nghị luận',
    summary: 'Bình luận về vai trò của học tập trong cuộc sống, cách học tập tốt để đạt kết quả cao. Nêu lý do tại sao phải chăm chỉ học...',
    views: 3450,
    date: '2024-06-20',
  },
  {
    id: '5',
    title: 'Phân tích nhân vật Hai Bà Trưng',
    author: 'Linh Giang',
    classLevel: '7',
    category: 'phân tích',
    summary: 'Phân tích tính cách, hành động của hai vị anh hùng Hai Bà Trưng qua các chi tiết trong tác phẩm văn học cổ điển...',
    views: 1890,
    date: '2024-06-18',
  },
  {
    id: '6',
    title: 'Những giá trị của truyền thống tết',
    author: 'Hương Thảo',
    classLevel: '7',
    category: 'nghị luận',
    summary: 'Luận về ý nghĩa của Tết cổ truyền đối với nền văn hóa Việt, những phong tục tập quán cần giữ lại...',
    views: 2670,
    date: '2024-06-12',
  },
  {
    id: '7',
    title: 'Câu chuyện lần đầu tiên đi học xa',
    author: 'Minh Phương',
    classLevel: '8',
    category: 'biểu cảm',
    summary: 'Bài văn viết về những cảm xúc, lo lắng, phấn khích khi lần đầu tiên đi học xa nhà, sống ký túc xá...',
    views: 3210,
    date: '2024-06-25',
  },
  {
    id: '8',
    title: 'Một chuyến đi ngoại khóa không quên',
    author: 'Thanh Vân',
    classLevel: '8',
    category: 'tự sự',
    summary: 'Kể chuyện về chuyến ngoại khóa đầy bất ngờ, những sự cố vui nhộn và những bài học quý giá từ chuyến đi...',
    views: 2890,
    date: '2024-06-22',
  },
  {
    id: '9',
    title: 'Về cấu tạo của hoa',
    author: 'Hoàng Anh',
    classLevel: '8',
    category: 'thuyết minh',
    summary: 'Thuyết minh chi tiết về các bộ phận cấu tạo hoa, chức năng của từng bộ phận, quá trình sinh sản của thực vật...',
    views: 1540,
    date: '2024-06-19',
  },
  {
    id: '10',
    title: 'Lý do tại sao chúng ta nên bảo vệ môi trường',
    author: 'Gia Huy',
    classLevel: '8',
    category: 'nghị luận',
    summary: 'Luận về hiện trạng ô nhiễm môi trường, tác hại của nó, và những cách thức để bảo vệ môi trường xanh...',
    views: 4120,
    date: '2024-06-21',
  },
  {
    id: '11',
    title: 'Phân tích tác phẩm Dế Mèn phiêu lưu ký',
    author: 'Huy Hoàng',
    classLevel: '8',
    category: 'phân tích',
    summary: 'Phân tích sâu sắc về nhân vật Dế Mèn, ý nghĩa biểu tượng của tác phẩm, những bài học rút ra từ cuộc phiêu lưu...',
    views: 3670,
    date: '2024-06-17',
  },
  {
    id: '12',
    title: 'Người mẹ của tôi',
    author: 'Thảo Nhi',
    classLevel: '8',
    category: 'biểu cảm',
    summary: 'Bài văn bộc lộ tình cảm yêu thương dành cho mẹ, những hy sinh và yêu thương mà mẹ dành cho con...',
    views: 5230,
    date: '2024-06-23',
  },
  {
    id: '13',
    title: 'Kỳ thi cuối kỳ I - Những cảm xúc hỗn tạp',
    author: 'Minh Tuấn',
    classLevel: '9',
    category: 'biểu cảm',
    summary: 'Viết về những cảm xúc phức tạp trước, trong và sau kỳ thi quan trọng cuối kỳ lần I...',
    views: 2340,
    date: '2024-06-24',
  },
  {
    id: '14',
    title: 'Hành trình chuẩn bị thi vào lớp 10',
    author: 'Khánh Linh',
    classLevel: '9',
    category: 'tự sự',
    summary: 'Kể chuyện những ngày ôn luyện, những khó khăn gặp phải và cách vượt qua để chuẩn bị cho kỳ thi vào lớp 10...',
    views: 4560,
    date: '2024-06-26',
  },
  {
    id: '15',
    title: 'Về đặc điểm của các tác phẩm cổ điển Việt Nam',
    author: 'Hà Nội',
    classLevel: '9',
    category: 'thuyết minh',
    summary: 'Giới thiệu những đặc điểm nổi bật của các tác phẩm cổ điển như Truyện Kiều, Tây Du Ký Việt Nam...',
    views: 1820,
    date: '2024-06-14',
  },
  {
    id: '16',
    title: 'Tại sao tuổi trẻ cần có ước mơ',
    author: 'Văn Anh',
    classLevel: '9',
    category: 'nghị luận',
    summary: 'Luận về tầm quan trọng của ước mơ đối với thanh niên, cách mà ước mơ thúc đẩy sự phát triển cá nhân...',
    views: 3890,
    date: '2024-06-27',
  },
  {
    id: '17',
    title: 'Phân tích nhân vật Kim Vân Kiều',
    author: 'Thanh Sơn',
    classLevel: '9',
    category: 'phân tích',
    summary: 'Phân tích chi tiết về tính cách, số phận và những học được từ nhân vật Kim Vân Kiều của Nguyễn Du...',
    views: 2950,
    date: '2024-06-28',
  },
  {
    id: '18',
    title: 'Sự ảnh hưởng của công nghệ số đến giới trẻ',
    author: 'Phương Anh',
    classLevel: '9',
    category: 'nghị luận',
    summary: 'Bình luận về tác động tích cực và tiêu cực của công nghệ số, cách sử dụng công nghệ một cách hợp lý...',
    views: 3450,
    date: '2024-06-29',
  },
  {
    id: '19',
    title: 'Chuyến du học nước ngoài - Kỷ niệm còn mãi',
    author: 'Hoàng Phúc',
    classLevel: '6',
    category: 'tự sự',
    summary: 'Kể chuyện về chuyến du học nước ngoài tuyệt vời, những trải nghiệm mới lạ và những bạn bè quốc tế...',
    views: 2120,
    date: '2024-06-30',
  },
  {
    id: '20',
    title: 'Hạnh phúc là gì',
    author: 'Gia Linh',
    classLevel: '7',
    category: 'biểu cảm',
    summary: 'Bài viết suy ngẫm về khái niệm hạnh phúc, những điều tạo nên hạnh phúc thực sự trong cuộc sống...',
    views: 4780,
    date: '2024-07-01',
  },
]
